kind: Deployment
metadata:
  name: zaman
  namespace: groups-node
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: node:14
        ports:
        - containerPort: 3000
        command: ["node", "-e", "require('http').createServer((req, res) => res.end('Hello from Node.js!')).listen(3000)"]
