apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: zaman
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30010
